INSERT INTO email_templates
VALUES (
    gen_random_uuid(),
    '2023-09-02 02:06:22',
    '2023-09-02 02:06:22',
    '{0}',
    '{0}',
    'off',
    'Case Closure',
    'Template for informing a contact that their case has been closed.',
    '$acase_name [CASE:$acase_case_number] closed',
    E'Hi $contact_first_name $contact_last_name,\n\n					   Your case $acase_name (# $acase_case_number) has been closed on $acase_date_entered\n					   Status:				$acase_status\n					   Reference:			$acase_case_number\n					   Resolution:			$acase_resolution',
    E'<p> Hi $contact_first_name $contact_last_name,</p>\n					    <p>Your case $acase_name (# $acase_case_number) has been closed on $acase_date_entered</p>\n					    <table border=\"0\"><tbody>\n					    <tr><td>Status</td><td>$acase_status</td></tr>\n					    <tr><td>Reference</td><td>$acase_case_number</td></tr>\n					    <tr><td>Resolution</td><td>$acase_resolution</td></tr>\n					    </tbody></table>',
    false,
    NULL,
    false,
    'system'
  ),
(
    gen_random_uuid(),
    '2023-09-02 02:06:22',
    '2023-09-02 02:06:22',
    '{0}',
    '{0}',
    'off',
    'Joomla Account Creation',
    E'Template used when informing a contact that they\'ve been given an account on the joomla portal.',
    'Support Portal Account Created',
    E'Hi $contact_name,\n					   An account has been created for you at $portal_address.\n					   You may login using this email address and the password $joomla_pass',
    E'<p>Hi $contact_name,</p>\n					    <p>An account has been created for you at <a href=\"$portal_address\">$portal_address</a>.</p>\n					    <p>You may login using this email address and the password $joomla_pass</p>',
    false,
    NULL,
    false,
    'system'
  ),
(
    gen_random_uuid(),
    '2023-09-02 02:06:22',
    '2023-09-02 02:06:22',
    '{0}',
    '{0}',
    'off',
    'Case Creation',
    'Template to send to a contact when a case is received from them.',
    '$acase_name [CASE:$acase_case_number]',
    E'Hi $contact_first_name $contact_last_name,\n\n					   We\'ve received your case $acase_name (# $acase_case_number) on $acase_date_entered\n					   Status:		$acase_status\n					   Reference:	$acase_case_number\n					   Description:	$acase_description',
    E'<p> Hi $contact_first_name $contact_last_name,</p>\n					    <p>We\'ve received your case $acase_name (# $acase_case_number) on $acase_date_entered</p>\n					    <table border=\"0\"><tbody>\n					    <tr><td>Status</td><td>$acase_status</td></tr>\n					    <tr><td>Reference</td><td>$acase_case_number</td></tr>\n					    <tr><td>Description</td><td>$acase_description</td></tr>\n					    </tbody></table>',
    false,
    NULL,
    false,
    'system'
  ),
(
    gen_random_uuid(),
    '2023-09-02 02:06:22',
    '2023-09-02 02:06:22',
    '{0}',
    '{0}',
    'off',
    'Contact Case Update',
    'Template to send to a contact when their case is updated.',
    '$acase_name update [CASE:$acase_case_number]',
    E'Hi $user_first_name $user_last_name,\n\n					   You\'ve had an update to your case $acase_name (# $acase_case_number) on $aop_case_updates_date_entered:\n					       $contact_first_name $contact_last_name, said:\n					               $aop_case_updates_description',
    E'<p>Hi $contact_first_name $contact_last_name,</p>\n					    <p> </p>\n					    <p>You\'ve had an update to your case $acase_name (# $acase_case_number) on $aop_case_updates_date_entered:</p>\n					    <p><strong>$user_first_name $user_last_name said:</strong></p>\n					    <p style=\"padding-left:30px;\">$aop_case_updates_description</p>',
    false,
    NULL,
    false,
    'system'
  ),
(
    gen_random_uuid(),
    '2023-09-02 02:06:22',
    '2023-09-02 02:06:22',
    '{0}',
    '{0}',
    'off',
    'User Case Update',
    'Email template to send to a SuiteCRM user when their case is updated.',
    '$acase_name (# $acase_case_number) update',
    E'Hi $user_first_name $user_last_name,\n\n					   You\'ve had an update to your case $acase_name (# $acase_case_number) on $aop_case_updates_date_entered:\n					       $contact_first_name $contact_last_name, said:\n					               $aop_case_updates_description\n                        You may review this Case at:\n                            $sugarurl/index.php?module=Cases&action=DetailView&record=$acase_id;',
    E'<p>Hi $user_first_name $user_last_name,</p>\n					     <p> </p>\n					     <p>You\'ve had an update to your case $acase_name (# $acase_case_number) on $aop_case_updates_date_entered:</p>\n					     <p><strong>$contact_first_name $contact_last_name, said:</strong></p>\n					     <p style=\"padding-left:30px;\">$aop_case_updates_description</p>\n					     <p>You may review this Case at: $sugarurl/index.php?module=Cases&action=DetailView&record=$acase_id;</p>',
    false,
    NULL,
    false,
    'system'
  ),
(
    gen_random_uuid(),
    '2013-05-24 14:31:45',
    '2023-09-02 02:06:22',
    '{0}',
    '{0}',
    'off',
    'Event Invite Template',
    'Default event invite template.',
    'You have been invited to $fp_events_name',
    E'Dear $contact_name,\nYou have been invited to $fp_events_name on $fp_events_date_start to $fp_events_date_end\n$fp_events_description\nYours Sincerely,\n',
    E'\n<p>Dear $contact_name,</p>\n<p>You have been invited to $fp_events_name on $fp_events_date_start to $fp_events_date_end</p>\n<p>$fp_events_description</p>\n<p>If you would like to accept this invititation please click accept.</p>\n<p> $fp_events_link or $fp_events_link_declined</p>\n<p>Yours Sincerely,</p>\n',
    false,
    NULL,
    false,
    'system'
  ),
(
    gen_random_uuid(),
    '2023-09-02 02:06:22',
    '2023-09-02 02:06:22',
    '{0}',
    '{0}',
    'off',
    'Confirmed Opt In',
    'Email template to send to a contact to confirm they have opted in.',
    'Confirm Opt In',
    E'Hi $contact_first_name $contact_last_name, \\n Please confirm that you have opted in by selecting the following link: $sugarurl/index.php?entryPoint=ConfirmOptIn&from=$emailaddress_email_address',
    E'<p>Hi $contact_first_name $contact_last_name,</p>\n             <p>\n                Please confirm that you have opted in by selecting the following link:\n                <a href=\"$sugarurl/index.php?entryPoint=ConfirmOptIn&from=$emailaddress_confirm_opt_in_token\">Opt In</a>\n             </p>',
    false,
    NULL,
    false,
    'system'
  ),
(
    gen_random_uuid(),
    '2023-09-02 02:06:22',
    '2023-09-02 02:06:22',
    '{0}',
    '{0}',
    'off',
    'System-generated password email',
    'This template is used when the System Administrator sends a new password to a user.',
    'New account information',
    E'\nHere is your account username and temporary password:\nUsername : $contact_user_user_name\nPassword : $contact_user_user_hash\n\n$config_site_url\n\nAfter you log in using the above password, you may be required to reset the password to one of your own choice.',
    E'<div><table width=\"550\"><tbody><tr><td><p>Here is your account username and temporary password:</p><p>Username : $contact_user_user_name </p><p>Password : $contact_user_user_hash </p><br /><p>$config_site_url</p><br /><p>After you log in using the above password, you may be required to reset the password to one of your own choice.</p>   </td>         </tr><tr><td></td>         </tr> </tbody></table> </div>',
    false,
    NULL,
    false,
    'system'
  ),
(
    gen_random_uuid(),
    '2023-09-02 02:06:22',
    '2023-09-02 02:06:22',
    '{0}',
    '{0}',
    'off',
    'Forgot Password email',
    E'This template is used to send a user a link to click to reset the user\'s account password.',
    'Reset your account password',
    E'\nYou recently requested on $contact_user_pwd_last_changed to be able to reset your account password.\n\nClick on the link below to reset your password:\n\n$contact_user_link_guid',
    E'<div><table width=\"550\"><tbody><tr><td><p>You recently requested on $contact_user_pwd_last_changed to be able to reset your account password. </p><p>Click on the link below to reset your password:</p><p> $contact_user_link_guid </p>  </td>         </tr><tr><td></td>         </tr> </tbody></table> </div>',
    false,
    NULL,
    false,
    'system'
  ),
(
    gen_random_uuid(),
    '2023-09-02 02:06:22',
    '2023-09-02 02:06:22',
    '{0}',
    '{0}',
    'off',
    'Two Factor Authentication email',
    'This template is used to send a user a code for Two Factor Authentication.',
    'Two Factor Authentication Code',
    E'Two Factor Authentication code is $code.',
    E'<div><table width=\"550\"><tbody><tr><td><p>Two Factor Authentication code is <b>$code</b>.</p>  </td>         </tr><tr><td></td>         </tr> </tbody></table> </div>',
    false,
    NULL,
    false,
    'system'
  );